metrics: true

resource-pack:
  # Whether autohosting is enabled; in case set to false and ResourcePackManager is installed, RSPM will be used.
  enabled: true

  # The protocol to use for the resource pack server (http or https).
  protocol: http

  # The IP address to bind the resource pack server to.
  ip: 5.83.140.143

  # The port to bind the resource pack server to.
  port: 8080

  # List of external resource pack paths to include.
  external_packs: []

# Adjust entity spawn limits per world category.
spawn_limits:
  monster: 70
  creature: 10
  ambient: 5
  water_creature: 10
  water_ambient: 5

permissions:
  # Storage type for permissions. Valid options: 'sqlite', 'mysql', 'mariadb', 'postgres', 'h2', 'mongodb', 'redis'
  storage_type: sqlite

  # SQL Database Settings (Used for mysql, mariadb, postgres)
  sql:
    host: 127.0.0.1
    port: 3306
    database: abyssallib
    username: root
    password: password

  # NoSQL Database Settings (Used for mongodb, redis)
  nosql:
    # URI for MongoDB or host for Redis
    uri: mongodb://localhost:27017

  # Local Database Settings (Used for sqlite, h2)
  local:
    # File name for local databases
    file: permissions.db

  # Web Editor Settings
  web:
    # Enable the web editor server.
    enabled: false

    # The protocol to use for the web editor (http or https).
    protocol: http

    # The IP address to bind the web editor to.
    ip: 127.0.0.1

    # The port to bind the web editor to.
    port: 8081
